defaults:
  aws:
    accessKeyId:        '...'
    secretAccessKey:    '...'
    region:             us-west-2
  app:
    # these must be in aws.region
    publicArtifactBucket: ...
    privateArtifactBucket: ...
  azure:
    accountId:        pamplemousse
    accessKey:         '...'
  pulse:
    username:           '...'
    password:           '...'
