apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${projectName}
  labels: {$eval: labels}
data:
  $merge:
    $map: {$eval: secrets}
    each(s):
      ${uppercase(s.key)}: '{{ if typeIs "<nil>" ${s.val} }}{{ else }}{{ if typeIs "string" ${s.val} }}{{ ${s.val} | b64enc }}{{ else }}{{ ${s.val} | toJson | b64enc }}{{ end }}{{ end }}'
